[package]
name = "sagate"
version = "0.1.0"
edition = "2021"
description = "A row-polymorphic language compiler for SQL"
license = "MIT"

[dependencies]
sqlglot-rust = "0.10.30"
unicode-ident = "1"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sagate"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
