[workspace]
resolver = "2"
members = [
    "crates/sagate-core",
    "crates/sagate-sql",
    "crates/sagate-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
sagate-core = { path = "crates/sagate-core", version = "0.1.0" }
sagate-sql = { path = "crates/sagate-sql", version = "0.1.0" }
sqlglot-rust = "0.10.30"
unicode-ident = "1"

[profile.release]
lto = true
codegen-units = 1
